web:
  build: .
  command: 'bash -c ''/app/src/scripts/build_nginx.sh'''
  working_dir: /app/src
  environment:
    PORT: 3000
  ports:
    - '3000:3000'
  volumes:
    - '.:/app/src'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
